# Site setting
title: MentorBot Docs
description: Docs for MentorBot

# Remote Setting
baseurl: ""
url: "https://vchristinne.github.io"
repository: just-the-docs/just-the-docs

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

# Theme
theme: just-the-docs

nav_enabled: true

back_to_top: true
back_to_top_text: "Voltar ao topo"

callouts:
  highlight:
    title: Highlight
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
